### ISSUE TITLE
Fake directories and directories in namespaces

### ISSUE THREAD

**Issue by leoc** [nicferrier/emacs-fakir#2]
First let me thank you for this lib. I´m learning a lot from reading your code.

I am in need of mocking `directory-files` and `directory-files-with-attributes`.

I´d love to implement this but wanted to ask you about your thoughts on mocking directories. For `directory-files` gives files and folders.
I´d simply add a `:directory-p` option to `fakir-file` struct and shadow `directory-files` and `directory-files-with-attributes` in the `fakir-fake-file` macro accordingly.

One other question I stumbled upon:

```
(fakir-fake-file
    (list
     (fakir-file
      :filename "blah"
      :directory "/home/fakir-test"
      :content "blah!")
     (fakir-file
      :filename "blah2"
      :directory "/home/fakir-test"
      :content "blah2!")
     (fakir-file
      :filename "blah3"
      :directory "/home/fakir-test"
      :content "NO WAY!")
     (fakir-file
      :filename "blah3"
      :directory "/tmp"
      :content "totally testing!"))
  (let ((real-home-dir
         (file-name-as-directory (getenv "HOME"))))
    (kvhash->alist fakir-file-namespace)))

=>

(("/tmp/blah3" . [cl-struct-fakir-file "blah3" "/tmp" "totally testing!" "Mon, Feb 27 2012 22:10:19 GMT"]) 
("/home/fakir-test/blah3" . [cl-struct-fakir-file "blah3" "/home/fakir-test" "NO WAY!" "Mon, Feb 27 2012 22:10:19 GMT"]) 
("/home/fakir-test/blah2" . [cl-struct-fakir-file "blah2" "/home/fakir-test" "blah2!" "Mon, Feb 27 2012 22:10:19 GMT"]) 
("/home/fakir-test/" . [cl-struct-fakir-file "blah" "/home/fakir-test" "blah!" "Mon, Feb 27 2012 22:10:19 GMT"]) 
("/home/fakir-test/blah" . [cl-struct-fakir-file "blah" "/home/fakir-test" "blah!" "Mon, Feb 27 2012 22:10:19 GMT"]))
```

Why is there "/home/fakir-test/" with content "blah!" ?

I would change that files `directory-p` to true when constructing the files-namespace. Also I suppose there should be a "/", "/home", "/tmp" file?

Cheers!

**Comment by nicferrier** [comment]
Seems like 2 issues.

1st issue is directory attributes, yes, just add the extra option and then shadow the binding. That seems like the right thing.

**Comment by nicferrier** [comment]
On the 2nd issue, hmmm. Maybe you could make another issue out of it and we could explore... but the alist is just the internal representation. Can you show an error with the file handling functions? do they actually break?

Thanks for reporting this... it looks like it could be a real bug.

**Comment by leoc** [comment]
I haven´t seen anything fail. I just wondered why there is this single directory in the namespace without a definition when calling the macro.

As I need those directories in the namespace I´d like to add those per default when defining functions. I will try to separate those concerns and create two pull requests :-)

**Comment by nicferrier** [comment]
Rocking. Thanks.
